"""Independent CRC self-test goldens -- AUTO-GENERATED, do not edit by hand.

Generated by ``scripts/gen_vectors.py``.  Each value is the CRC of one of four
fixed inputs, computed by TWO independent engines (anycrc + crccheck) that had
to agree, and (at the ``check`` input) anchored to reveng's published value.
The code generators embed these as self-test constants;
``tests/test_independent_vectors.py`` cross-checks crcglot's own engine.

Inputs: ``empty=b""``, ``check=b"123456789"``, ``all_bytes=bytes(range(256))``,
``binary_1k=bytes((i * 167 + 13) & 0xFF for i in range(1024))``.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from crcglot.catalogue import Crc

VECTORS: dict[str, dict[str, int]] = {
    "crc10-atm": {"empty": 0x000, "check": 0x199, "all_bytes": 0x22F, "binary_1k": 0x3BE},
    "crc10-cdma2000": {"empty": 0x3FF, "check": 0x233, "all_bytes": 0x0C6, "binary_1k": 0x071},
    "crc10-gsm": {"empty": 0x3FF, "check": 0x12A, "all_bytes": 0x3B4, "binary_1k": 0x19E},
    "crc11-flexray": {"empty": 0x01A, "check": 0x5A3, "all_bytes": 0x6DA, "binary_1k": 0x4CA},
    "crc11-umts": {"empty": 0x000, "check": 0x061, "all_bytes": 0x3A3, "binary_1k": 0x231},
    "crc12-cdma2000": {"empty": 0xFFF, "check": 0xD4D, "all_bytes": 0xE4A, "binary_1k": 0x322},
    "crc12-dect": {"empty": 0x000, "check": 0xF5B, "all_bytes": 0x780, "binary_1k": 0x1C2},
    "crc12-gsm": {"empty": 0xFFF, "check": 0xB34, "all_bytes": 0xE0A, "binary_1k": 0xC48},
    "crc12-umts": {"empty": 0x000, "check": 0xDAF, "all_bytes": 0x01E, "binary_1k": 0x438},
    "crc13-bbc": {"empty": 0x0000, "check": 0x04FA, "all_bytes": 0x1139, "binary_1k": 0x04E5},
    "crc14-darc": {"empty": 0x0000, "check": 0x082D, "all_bytes": 0x08AD, "binary_1k": 0x1C8C},
    "crc14-gsm": {"empty": 0x3FFF, "check": 0x30AE, "all_bytes": 0x1549, "binary_1k": 0x2295},
    "crc15-can": {"empty": 0x0000, "check": 0x059E, "all_bytes": 0x314A, "binary_1k": 0x16AE},
    "crc15-mpt1327": {"empty": 0x0001, "check": 0x2566, "all_bytes": 0x19BF, "binary_1k": 0x085A},
    "crc16-arc": {"empty": 0x0000, "check": 0xBB3D, "all_bytes": 0xBAD3, "binary_1k": 0xEB30},
    "crc16-cdma2000": {"empty": 0xFFFF, "check": 0x4C06, "all_bytes": 0xF8E6, "binary_1k": 0x548E},
    "crc16-cms": {"empty": 0xFFFF, "check": 0xAEE7, "all_bytes": 0xC65C, "binary_1k": 0xB77E},
    "crc16-dds-110": {"empty": 0x800D, "check": 0x9ECF, "all_bytes": 0xB5A1, "binary_1k": 0x44AA},
    "crc16-dect-r": {"empty": 0x0001, "check": 0x007E, "all_bytes": 0x9A1C, "binary_1k": 0x7AD1},
    "crc16-dect-x": {"empty": 0x0000, "check": 0x007F, "all_bytes": 0x9A1D, "binary_1k": 0x7AD0},
    "crc16-dnp": {"empty": 0xFFFF, "check": 0xEA82, "all_bytes": 0x4472, "binary_1k": 0xC360},
    "crc16-en-13757": {"empty": 0xFFFF, "check": 0xC2B7, "all_bytes": 0xB50D, "binary_1k": 0xA208},
    "crc16-genibus": {"empty": 0x0000, "check": 0xD64E, "all_bytes": 0xC042, "binary_1k": 0xDF75},
    "crc16-gsm": {"empty": 0xFFFF, "check": 0xCE3C, "all_bytes": 0x81AA, "binary_1k": 0x681A},
    "crc16-ibm-3740": {"empty": 0xFFFF, "check": 0x29B1, "all_bytes": 0x3FBD, "binary_1k": 0x208A},
    "crc16-ibm-sdlc": {"empty": 0x0000, "check": 0x906E, "all_bytes": 0x303C, "binary_1k": 0x8643},
    "crc16-iso-iec-14443-3-a": {"empty": 0x6363, "check": 0xBF05, "all_bytes": 0xFD76, "binary_1k": 0xF829},
    "crc16-kermit": {"empty": 0x0000, "check": 0x2189, "all_bytes": 0xD841, "binary_1k": 0x8F51},
    "crc16-lj1200": {"empty": 0x0000, "check": 0xBDF4, "all_bytes": 0x6EDE, "binary_1k": 0xD594},
    "crc16-m17": {"empty": 0xFFFF, "check": 0x772B, "all_bytes": 0x1C31, "binary_1k": 0x843E},
    "crc16-maxim": {"empty": 0xFFFF, "check": 0x44C2, "all_bytes": 0x452C, "binary_1k": 0x14CF},
    "crc16-mcrf4xx": {"empty": 0xFFFF, "check": 0x6F91, "all_bytes": 0xCFC3, "binary_1k": 0x79BC},
    "crc16-modbus": {"empty": 0xFFFF, "check": 0x4B37, "all_bytes": 0xDE6C, "binary_1k": 0x3F8E},
    "crc16-nrsc-5": {"empty": 0xFFFF, "check": 0xA066, "all_bytes": 0xC575, "binary_1k": 0xD087},
    "crc16-opensafety-a": {"empty": 0x0000, "check": 0x5D38, "all_bytes": 0x3403, "binary_1k": 0xF6CB},
    "crc16-opensafety-b": {"empty": 0x0000, "check": 0x20FE, "all_bytes": 0x405D, "binary_1k": 0x90CB},
    "crc16-profibus": {"empty": 0x0000, "check": 0xA819, "all_bytes": 0x73DE, "binary_1k": 0xF050},
    "crc16-riello": {"empty": 0x554D, "check": 0x63D0, "all_bytes": 0x8543, "binary_1k": 0xDD3F},
    "crc16-spi-fujitsu": {"empty": 0x1D0F, "check": 0xE5CC, "all_bytes": 0x3C8E, "binary_1k": 0x8D36},
    "crc16-t10-dif": {"empty": 0x0000, "check": 0xD0DB, "all_bytes": 0x563B, "binary_1k": 0x6326},
    "crc16-teledisk": {"empty": 0x0000, "check": 0x0FB3, "all_bytes": 0xE0B5, "binary_1k": 0xD57A},
    "crc16-tms37157": {"empty": 0x3791, "check": 0x26B1, "all_bytes": 0x8920, "binary_1k": 0x8863},
    "crc16-umts": {"empty": 0x0000, "check": 0xFEE8, "all_bytes": 0x3B7A, "binary_1k": 0xCA55},
    "crc16-usb": {"empty": 0x0000, "check": 0xB4C8, "all_bytes": 0x2193, "binary_1k": 0xC071},
    "crc16-xmodem": {"empty": 0x0000, "check": 0x31C3, "all_bytes": 0x7E55, "binary_1k": 0x97E5},
    "crc17-can-fd": {"empty": 0x00000, "check": 0x04F03, "all_bytes": 0x196F8, "binary_1k": 0x1FF4F},
    "crc21-can-fd": {"empty": 0x000000, "check": 0x0ED841, "all_bytes": 0x1F07E8, "binary_1k": 0x01B65C},
    "crc24-ble": {"empty": 0xAAAAAA, "check": 0xC25A56, "all_bytes": 0x62B6D7, "binary_1k": 0x8CAD05},
    "crc24-flexray-a": {"empty": 0xFEDCBA, "check": 0x7979BD, "all_bytes": 0x47588D, "binary_1k": 0x4D2F8D},
    "crc24-flexray-b": {"empty": 0xABCDEF, "check": 0x1F23B8, "all_bytes": 0xED7A27, "binary_1k": 0x698DF1},
    "crc24-interlaken": {"empty": 0x000000, "check": 0xB4F3E6, "all_bytes": 0x7F30D5, "binary_1k": 0x0539BE},
    "crc24-lte-a": {"empty": 0x000000, "check": 0xCDE703, "all_bytes": 0xD5549F, "binary_1k": 0x95AF8E},
    "crc24-lte-b": {"empty": 0x000000, "check": 0x23EF52, "all_bytes": 0x7FDB6B, "binary_1k": 0xCFFF5C},
    "crc24-openpgp": {"empty": 0xB704CE, "check": 0x21CF02, "all_bytes": 0x5BBD34, "binary_1k": 0x276DF7},
    "crc24-os-9": {"empty": 0x000000, "check": 0x200FA5, "all_bytes": 0x68AB1B, "binary_1k": 0xF6FF71},
    "crc3-gsm": {"empty": 0x7, "check": 0x4, "all_bytes": 0x2, "binary_1k": 0x0},
    "crc3-rohc": {"empty": 0x7, "check": 0x6, "all_bytes": 0x6, "binary_1k": 0x5},
    "crc30-cdma": {"empty": 0x00000000, "check": 0x04C34ABF, "all_bytes": 0x08189A6E, "binary_1k": 0x22790094},
    "crc31-philips": {"empty": 0x00000000, "check": 0x0CE9E46C, "all_bytes": 0x58616F16, "binary_1k": 0x186A522F},
    "crc32": {"empty": 0x00000000, "check": 0xCBF43926, "all_bytes": 0x29058C73, "binary_1k": 0x6D4552DB},
    "crc32-aixm": {"empty": 0x00000000, "check": 0x3010BF7F, "all_bytes": 0xAB16EA85, "binary_1k": 0x308CF629},
    "crc32-autosar": {"empty": 0x00000000, "check": 0x1697D06A, "all_bytes": 0xAA61F4B7, "binary_1k": 0xB8149D13},
    "crc32-bacnet": {"empty": 0x00000000, "check": 0x2D3DD0AE, "all_bytes": 0xABC0D366, "binary_1k": 0x3A14C977},
    "crc32-base91-d": {"empty": 0x00000000, "check": 0x87315576, "all_bytes": 0x6165003E, "binary_1k": 0x9D1C374D},
    "crc32-bzip2": {"empty": 0x00000000, "check": 0xFC891918, "all_bytes": 0xB6B5EE95, "binary_1k": 0x646333CA},
    "crc32-cd-rom-edc": {"empty": 0x00000000, "check": 0x6EC2EDC4, "all_bytes": 0xE377019A, "binary_1k": 0xEB584FED},
    "crc32-cksum": {"empty": 0xFFFFFFFF, "check": 0x765E7680, "all_bytes": 0x53EB78DA, "binary_1k": 0xEF6961C2},
    "crc32-iscsi": {"empty": 0x00000000, "check": 0xE3069283, "all_bytes": 0x9C44184B, "binary_1k": 0xCB2740B2},
    "crc32-jamcrc": {"empty": 0xFFFFFFFF, "check": 0x340BC6D9, "all_bytes": 0xD6FA738C, "binary_1k": 0x92BAAD24},
    "crc32-mef": {"empty": 0xFFFFFFFF, "check": 0xD2C22F51, "all_bytes": 0x543F2C99, "binary_1k": 0xC5EB3688},
    "crc32-mpeg-2": {"empty": 0xFFFFFFFF, "check": 0x0376E6E7, "all_bytes": 0x494A116A, "binary_1k": 0x9B9CCC35},
    "crc32-xfer": {"empty": 0x00000000, "check": 0xBD0BE338, "all_bytes": 0x3FF2756B, "binary_1k": 0x96E8DB25},
    "crc4-g-704": {"empty": 0x0, "check": 0x7, "all_bytes": 0x5, "binary_1k": 0x4},
    "crc4-interlaken": {"empty": 0x0, "check": 0xB, "all_bytes": 0x7, "binary_1k": 0x3},
    "crc5-epc-c1g2": {"empty": 0x09, "check": 0x00, "all_bytes": 0x02, "binary_1k": 0x1B},
    "crc5-g-704": {"empty": 0x00, "check": 0x07, "all_bytes": 0x05, "binary_1k": 0x1D},
    "crc5-usb": {"empty": 0x00, "check": 0x19, "all_bytes": 0x08, "binary_1k": 0x0A},
    "crc6-cdma2000-a": {"empty": 0x3F, "check": 0x0D, "all_bytes": 0x09, "binary_1k": 0x37},
    "crc6-cdma2000-b": {"empty": 0x3F, "check": 0x3B, "all_bytes": 0x24, "binary_1k": 0x1D},
    "crc6-darc": {"empty": 0x00, "check": 0x26, "all_bytes": 0x33, "binary_1k": 0x1E},
    "crc6-g-704": {"empty": 0x00, "check": 0x06, "all_bytes": 0x2D, "binary_1k": 0x0E},
    "crc6-gsm": {"empty": 0x3F, "check": 0x13, "all_bytes": 0x2E, "binary_1k": 0x11},
    "crc64-ecma-182": {"empty": 0x0000000000000000, "check": 0x6C40DF5F0B497347, "all_bytes": 0x62B0DA1C1B130A91, "binary_1k": 0x69067A95A08E919F},
    "crc64-go-iso": {"empty": 0x0000000000000000, "check": 0xB90956C775A41001, "all_bytes": 0x89F7EAA7B75C07DD, "binary_1k": 0xDBCAE97AC09F4FBB},
    "crc64-ms": {"empty": 0xFFFFFFFFFFFFFFFF, "check": 0x75D4B74F024ECEEA, "all_bytes": 0x73010E7725BCD180, "binary_1k": 0x43499263A8D2AB94},
    "crc64-nvme": {"empty": 0x0000000000000000, "check": 0xAE8B14860A799888, "all_bytes": 0xFF71E21279D9966E, "binary_1k": 0x98D229B278D02BD3},
    "crc64-redis": {"empty": 0x0000000000000000, "check": 0xE9C6D914C4B8D9CA, "all_bytes": 0x88BFA574E806500E, "binary_1k": 0xAF435A2AB754FF8A},
    "crc64-we": {"empty": 0x0000000000000000, "check": 0x62EC59E3F1A4F00A, "all_bytes": 0x59C3325B2927A19A, "binary_1k": 0x59E2EC9149488F5C},
    "crc64-xz": {"empty": 0x0000000000000000, "check": 0x995DC9BBDF1939FA, "all_bytes": 0x72414B2F65DB3AB0, "binary_1k": 0xE2504255C8F21546},
    "crc7-mmc": {"empty": 0x00, "check": 0x75, "all_bytes": 0x78, "binary_1k": 0x3B},
    "crc7-rohc": {"empty": 0x7F, "check": 0x53, "all_bytes": 0x4C, "binary_1k": 0x73},
    "crc7-umts": {"empty": 0x00, "check": 0x61, "all_bytes": 0x22, "binary_1k": 0x0A},
    "crc8": {"empty": 0x00, "check": 0xF4, "all_bytes": 0x14, "binary_1k": 0x09},
    "crc8-autosar": {"empty": 0x00, "check": 0xDF, "all_bytes": 0x06, "binary_1k": 0xD7},
    "crc8-bacnet": {"empty": 0x00, "check": 0x89, "all_bytes": 0x4C, "binary_1k": 0x86},
    "crc8-bluetooth": {"empty": 0x00, "check": 0x26, "all_bytes": 0xC9, "binary_1k": 0x72},
    "crc8-cdma2000": {"empty": 0xFF, "check": 0xDA, "all_bytes": 0x41, "binary_1k": 0x2B},
    "crc8-darc": {"empty": 0x00, "check": 0x15, "all_bytes": 0x3C, "binary_1k": 0x58},
    "crc8-dvb-s2": {"empty": 0x00, "check": 0xBC, "all_bytes": 0xCA, "binary_1k": 0xEE},
    "crc8-gsm-a": {"empty": 0x00, "check": 0x37, "all_bytes": 0x3E, "binary_1k": 0xB5},
    "crc8-gsm-b": {"empty": 0xFF, "check": 0x94, "all_bytes": 0x0C, "binary_1k": 0x9A},
    "crc8-hitag": {"empty": 0xFF, "check": 0xB4, "all_bytes": 0xFA, "binary_1k": 0x13},
    "crc8-i-432-1": {"empty": 0x55, "check": 0xA1, "all_bytes": 0x41, "binary_1k": 0x5C},
    "crc8-i-code": {"empty": 0xFD, "check": 0x7E, "all_bytes": 0xC0, "binary_1k": 0x34},
    "crc8-lte": {"empty": 0x00, "check": 0xEA, "all_bytes": 0xF0, "binary_1k": 0xFF},
    "crc8-maxim": {"empty": 0x00, "check": 0xA1, "all_bytes": 0x18, "binary_1k": 0xB7},
    "crc8-mifare-mad": {"empty": 0xC7, "check": 0x99, "all_bytes": 0x58, "binary_1k": 0xE0},
    "crc8-nrsc-5": {"empty": 0xFF, "check": 0xF7, "all_bytes": 0x14, "binary_1k": 0x78},
    "crc8-opensafety": {"empty": 0x00, "check": 0x3E, "all_bytes": 0x41, "binary_1k": 0xF6},
    "crc8-rohc": {"empty": 0xFF, "check": 0xD0, "all_bytes": 0x8E, "binary_1k": 0x93},
    "crc8-sae-j1850": {"empty": 0x00, "check": 0x4B, "all_bytes": 0x05, "binary_1k": 0xEC},
    "crc8-tech-3250": {"empty": 0xFF, "check": 0x97, "all_bytes": 0xC5, "binary_1k": 0x67},
    "crc8-wcdma": {"empty": 0x00, "check": 0x25, "all_bytes": 0x59, "binary_1k": 0x33},
}


_BY_PARAMS: dict[tuple[int, int, int, bool, bool, int], dict[str, int]] | None = None


def goldens_for(crc: "Crc") -> dict[str, int] | None:
    """The four self-test goldens for a catalogue ``Crc`` / ``AlgorithmInfo``.

    Keyed by parameter tuple so a renamed catalogue algorithm still resolves;
    returns ``None`` for a custom (non-catalogue) polynomial.
    """
    global _BY_PARAMS
    if _BY_PARAMS is None:
        from crcglot.catalogue import ALGORITHMS
        _BY_PARAMS = {
            (a.width, a.poly, a.init, a.refin, a.refout, a.xorout): VECTORS[n]
            for n, a in ALGORITHMS.items() if n in VECTORS
        }
    return _BY_PARAMS.get(
        (crc.width, crc.poly, crc.init, crc.refin, crc.refout, crc.xorout)
    )
