"""The committed self-test goldens are a current two-oracle regeneration.

``src/crcglot/_vectors.py`` is generated by ``scripts/gen_vectors.py``, which
computes every value with two independent engines (anycrc + crccheck) that must
agree and anchors the ``check`` input to reveng.  That agreement is enforced
when the file is regenerated, which is a manual step.  ``test_independent_vectors``
then pins crcglot's own engine to the committed values, and
``test_external_vectors`` pins the engine to other authorities (zlib, reveng,
BACnet, AUTOSAR).  What none of those re-run is the two-oracle agreement itself,
so "anycrc and crccheck agreed" was, until this file, generation-time provenance
rather than a live fact.

This file closes that loop: it re-runs the exact generation logic
(``gen_vectors.compute_vectors``) and asserts it reproduces the committed file
value for value.  A green run is live proof that the two oracles still agree, the
reveng anchor still holds, and the checked-in file is not stale.  A catalogue
parameter edited without a regenerate, a hand-edit, or an oracle regression all
surface here instead of riding along silently.

Two implementation notes:

1. The regeneration runs in a **subprocess**, not in-process.  ``compute_vectors``
   drives crccheck (pure Python) over the whole catalogue, ~5s natively but ~25x
   that under the suite's ``--cov`` line tracer.  A clean child process is not
   traced, so it runs at the same cost as ``gen_vectors.py`` itself.  Because it
   shells out, the regeneration test is ``@pytest.mark.slow`` (pre-merge full
   suite, not the fast tier), matching the convention for subprocess tests.
2. The oracles are dev-only, so the child imports the generation script (which
   imports anycrc / crccheck) directly -- a hard import, never ``importorskip``:
   a missing oracle must fail loudly, not skip into a false green.
"""

from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path

import pytest

from crcglot._vectors import VECTORS

_GEN = Path(__file__).resolve().parent.parent / "scripts" / "gen_vectors.py"

# Child program: load the generation script by path, run the real two-oracle
# regeneration, and emit it as JSON.  A ValueError (oracle disagreement / anchor
# failure) propagates as a non-zero exit with a traceback on stderr.
_REGEN_CHILD = (
    "import json, sys, importlib.util;"
    "spec = importlib.util.spec_from_file_location('gv', sys.argv[1]);"
    "m = importlib.util.module_from_spec(spec);"
    "spec.loader.exec_module(m);"
    "print(json.dumps(m.compute_vectors()))"
)


def _load_gen_vectors():
    """Import ``scripts/gen_vectors.py`` by path (``scripts/`` is not a package).

    Mirrors the importlib-by-path idiom in ``test_oracle_mutation.py``; executing
    the module body runs its top-level imports but not ``main()``.
    """
    spec = importlib.util.spec_from_file_location("gen_vectors", _GEN)
    assert spec is not None and spec.loader is not None, "gen_vectors must load"
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


class TestTwoOracleProvenance:
    """The committed goldens equal a fresh two-oracle, reveng-anchored regen."""

    @pytest.mark.slow
    def test_committed_goldens_match_fresh_regeneration(self) -> None:
        # Act -- regenerate in a clean (untraced) child via the real generation
        # logic.  A non-zero exit means the two oracles disagreed or the reveng
        # anchor failed (compute_vectors raises ValueError), which is itself a
        # regression worth surfacing.
        proc = subprocess.run(
            [sys.executable, "-c", _REGEN_CHILD, str(_GEN)],
            capture_output=True, text=True,
        )
        assert proc.returncode == 0, (
            f"regeneration aborted (oracle disagreement or reveng-anchor "
            f"failure):\n{proc.stderr[-2000:]}"
        )
        actual = json.loads(proc.stdout)
        expected = dict(VECTORS)

        # Assert -- coverage first (which algorithms), then per-value equality.
        assert actual.keys() == expected.keys(), (
            f"regeneration covers different algorithms than the committed file: "
            f"missing={expected.keys() - actual.keys()}, "
            f"extra={actual.keys() - expected.keys()} -- "
            f"regenerate with scripts/gen_vectors.py"
        )
        mismatches = {
            name: {
                inp: (actual[name][inp], expected[name][inp])
                for inp in expected[name]
                if actual[name][inp] != expected[name][inp]
            }
            for name in expected
            if actual[name] != expected[name]
        }
        assert not mismatches, (
            f"committed _vectors.py is stale: a fresh two-oracle regeneration "
            f"differs at {mismatches} (fresh, committed) -- "
            f"regenerate with scripts/gen_vectors.py"
        )

    def test_oracle_disagreement_aborts_regeneration(self, monkeypatch) -> None:
        """The agreement check has teeth: a disagreeing oracle aborts the regen.

        Guards the guard.  Without this, a refactor that dropped the
        anycrc==crccheck comparison would leave the regeneration test green (both
        oracles still happen to agree), so the agreement would silently stop
        being checked.  Runs in-process and cheap: the corruption forces an abort
        on the very first algorithm, so no large-input crccheck pass occurs.
        """
        # Arrange -- force crccheck to disagree with anycrc on every value; ^1
        # keeps the result in-domain and guarantees a difference.
        gv = _load_gen_vectors()
        original = gv._crccheck_calc
        monkeypatch.setattr(
            gv, "_crccheck_calc", lambda a, data: original(a, data) ^ 1
        )

        # Act / Assert -- the very first algorithm must abort the regeneration.
        with pytest.raises(ValueError, match="ORACLE DISAGREEMENT"):
            gv.compute_vectors()
