"""Verilog CRC generator (SystemVerilog 2012 dialect).

Emits a single ``.sv`` file containing a ``package`` with five
functions:

  - ``<fname>_init`` -- return the starting state ([W-1:0])
  - ``<fname>_update(state, byte_in)`` -- feed one byte, return new state
  - ``<fname>_finalize(state)`` -- apply output reflection + xorout
  - ``<fname>(data)`` -- one-shot wrapper over a ``byte data[]``
    dynamic array
  - ``<fname>_self_test`` -- returns ``1'b1`` iff the algorithm
    reproduces the reveng catalogue check value for ``"123456789"``

Wrapped in ``package <fname>_pkg ... endpackage`` so a testbench can
``import <fname>_pkg::*;`` and call the functions directly.  Compiled
under ``iverilog -g2012`` (SystemVerilog 2012); the same construct
works under Verilator and modern commercial simulators.

Scope note: like the VHDL target, this is a simulator-friendly
reference implementation -- pure combinational functions over packed
bit vectors.  Synthesizable pipelined RTL (always_ff blocks, a real
hardware datapath) is a future enhancement; the function-in-package
form is the right shape for "verified reference implementation",
not a drop-in synthesizable IP block.

Verified at build time by ``tests.test_verilog_gen
.TestGeneratedVerilogExecutes`` (one-shot path via iverilog + vvp).
"""

# ruff: noqa: F541  - f-strings without placeholders used for code alignment

from __future__ import annotations

from typing import Literal

from crcglot._helpers import _func_name, _hex, _variant_to_flags
from crcglot.catalogue import ALGORITHMS, AlgorithmInfo, _reflect


def _sv_lit(value: int, width: int) -> str:
    """Format an integer constant as a SystemVerilog sized hex literal."""
    hex_w = (width + 3) // 4
    return f"{width}'h{value:0{hex_w}X}"


def _self_test_sv(fname: str, check: int, width: int) -> list[str]:
    """Emit a SystemVerilog self_test function returning 1'b1 on success.

    The reveng check input ``"123456789"`` is hardcoded as a byte
    array literal; the function returns the comparison result so a
    testbench can do ``assert (<fname>_self_test());`` or use it in
    any boolean context.
    """
    return [
        f"",
        f"    // Run the canonical reveng check value; returns 1'b1 on success.",
        f"    function automatic bit {fname}_self_test();",
        f"        byte unsigned data[] = '{{",
        f"            8'h31, 8'h32, 8'h33, 8'h34, 8'h35,",
        f"            8'h36, 8'h37, 8'h38, 8'h39",
        f"        }};",
        f"        return ({fname}(data) == {_sv_lit(check, width)});",
        f"    endfunction",
    ]


def generate_verilog(
    name: str,
    symbol: str | None = None,
    variant: Literal["bitwise"] = "bitwise",
) -> str | None:
    """Look up a CRC algorithm by name and generate a Verilog package.

    Thin wrapper around :func:`generate_verilog_from_entry`; use the
    latter directly for custom (non-catalogue) algorithm specs.
    """
    algo = ALGORITHMS.get(name)
    if algo is None:
        return None
    return generate_verilog_from_entry(name, algo, symbol=symbol, variant=variant)


def generate_verilog_from_entry(
    name: str,
    algo: AlgorithmInfo,
    symbol: str | None = None,
    variant: Literal["bitwise"] = "bitwise",
) -> str:
    """Generate a SystemVerilog package from an :class:`AlgorithmInfo`.

    Args:
        name: Algorithm name (used in comments).
        algo: Algorithm parameters as a typed :class:`AlgorithmInfo`.
        symbol: Optional override for the generated function name
            (default: ``_func_name(name)``).  Package name derives
            from the symbol.
        variant: Always ``"bitwise"`` -- accepted for API symmetry with
            the other generators.  Passing ``"table"`` or ``"slice8"``
            raises ``ValueError`` (table-driven Verilog deferred, same
            scope decision as VHDL).

    Returns:
        SystemVerilog source string.
    """
    _variant_to_flags(variant, allow_table=False, allow_slice8=False)
    w = algo.width
    poly = algo.poly
    init = algo.init
    refin = algo.refin
    refout = algo.refout
    xorout = algo.xorout
    check = algo.check
    desc = algo.desc
    fname = symbol if symbol else _func_name(name)
    pkg = f"{fname}_pkg"

    if refin:
        init_state = _reflect(init, w)
        poly_val = _reflect(poly, w)
    else:
        init_state = init
        poly_val = poly

    lines: list[str] = [
        f"// {fname}.sv -- generated by crcglot from reveng/{name}",
        f"// {desc}",
        f"// check: crc(\"123456789\") == {_hex(check, w)}",
        f"//",
        f"// Streaming: init -> update (one byte at a time) -> finalize.",
        f"// One-shot:  {fname}(data) where ``data`` is a byte[] array.",
        f"// Verify:    call {fname}_self_test in a testbench.",
        f"",
        f"`ifndef {pkg.upper()}_SV",
        f"`define {pkg.upper()}_SV",
        f"",
        f"package {pkg};",
    ]

    # ---- <fname>_init ----
    lines += [
        f"",
        f"    function automatic [{w - 1}:0] {fname}_init();",
        f"        {fname}_init = {_sv_lit(init_state, w)};",
        f"    endfunction",
    ]

    # ---- <fname>_update(state, byte_in) ----
    # Single-byte update -- caller loops over data themselves.  This
    # matches the streaming-friendly shape (callers can feed bytes
    # as they arrive without pre-buffering).
    lines += [
        f"",
        f"    function automatic [{w - 1}:0] {fname}_update("
        f"input [{w - 1}:0] state, input [7:0] byte_in);",
        f"        logic [{w - 1}:0] crc;",
        f"        crc = state;",
    ]
    if refin:
        # Reflected: XOR byte into low byte, then right-shift loop.
        if w == 8:
            # For w=8 the resize is trivial; no shift needed for the XOR.
            lines += [
                f"        crc = crc ^ byte_in;",
            ]
        else:
            lines += [
                f"        crc = crc ^ {{{{{w - 8}{{1'b0}}}}, byte_in}};",
            ]
        lines += [
            f"        for (int j = 0; j < 8; j++) begin",
            f"            if (crc[0])",
            f"                crc = (crc >> 1) ^ {_sv_lit(poly_val, w)};",
            f"            else",
            f"                crc = crc >> 1;",
            f"        end",
        ]
    else:
        # Non-reflected: XOR byte into high byte, then left-shift loop.
        if w == 8:
            lines += [
                f"        crc = crc ^ byte_in;",
            ]
        else:
            lines += [
                f"        crc = crc ^ ({{{{{w - 8}{{1'b0}}}}, byte_in}} << {w - 8});",
            ]
        lines += [
            f"        for (int j = 0; j < 8; j++) begin",
            f"            if (crc[{w - 1}])",
            f"                crc = (crc << 1) ^ {_sv_lit(poly_val, w)};",
            f"            else",
            f"                crc = crc << 1;",
            f"        end",
        ]
    lines += [
        f"        {fname}_update = crc;",
        f"    endfunction",
    ]

    # ---- <fname>_finalize(state) ----
    lines += [
        f"",
        f"    function automatic [{w - 1}:0] {fname}_finalize("
        f"input [{w - 1}:0] state);",
        f"        logic [{w - 1}:0] crc;",
        f"        crc = state;",
    ]
    if refout != refin:
        lines += [
            f"        // reflect output (refout != refin)",
            f"        begin : reflect",
            f"            logic [{w - 1}:0] reflected;",
            f"            reflected = '0;",
            f"            for (int k = 0; k < {w}; k++)",
            f"                reflected[k] = crc[{w - 1} - k];",
            f"            crc = reflected;",
            f"        end",
        ]
    if xorout:
        lines.append(f"        {fname}_finalize = crc ^ {_sv_lit(xorout, w)};")
    else:
        lines.append(f"        {fname}_finalize = crc;")
    lines.append(f"    endfunction")

    # ---- one-shot ----
    lines += [
        f"",
        f"    function automatic [{w - 1}:0] {fname}("
        f"input byte unsigned data[]);",
        f"        logic [{w - 1}:0] s;",
        f"        s = {fname}_init();",
        f"        foreach (data[i])",
        f"            s = {fname}_update(s, data[i]);",
        f"        {fname} = {fname}_finalize(s);",
        f"    endfunction",
    ]

    # ---- self-test ----
    lines.extend(_self_test_sv(fname, check, w))

    lines += [
        f"",
        f"endpackage",
        f"",
        f"`endif",
    ]

    return "\n".join(lines)
