"""Google-style Python docstrings (``Args:`` / ``Returns:`` / ``Note:``).

The docstring convention CLAUDE.md mandates for the project's own code.
Python-only; overrides the two hooks, so ``python.py`` is unchanged.
"""

from __future__ import annotations

from crcglot._helpers import _hex

from .base import CommentStyle, _param_summary, _render
from .model import AlgoMeta, DocBlock, UsageExample


def _google_block_body(block: DocBlock) -> list[str]:
    """A function docstring in Google style (``Args:`` / ``Returns:`` / ...)."""
    body = [block.summary]
    if block.params:
        body += ["", "Args:"]
        for p in block.params:
            body.append(f"    {p.name}: {p.text}")
    if block.returns:
        body += ["", "Returns:", f"    {block.returns}"]
    if block.notes:
        body += ["", "Note:"]
        for note in block.notes:
            body.append(f"    {note}")
    return body


def _google_header_body(meta: AlgoMeta, usage: UsageExample) -> list[str]:
    """The module overview as a Google-style docstring with an Example section."""
    body = [
        f"{meta.name} -- {meta.desc}",
        "",
        f"Parameters: {_param_summary(meta)}.",
        f"check: {usage.oneshot} over \"123456789\" == "
        f"{_hex(meta.check, meta.width)}",
        "",
        "Example:",
        "    Streaming -- call init, then update over each chunk, then finalize::",
        "",
    ]
    body += ["        " + ln for ln in usage.streaming]
    body += ["", f"    One-shot: {usage.oneshot}"]
    notes = [
        f"Verify with {usage.selftest} ({usage.selftest_returns}); run it once "
        "on your interpreter to catch a build / width mismatch.",
    ]
    notes += list(usage.caveats)
    notes.append(
        f"Generated by crcglot from reveng/{meta.name} -- a verified "
        "reference implementation."
    )
    body.append("")
    body.append("Note:")
    for n in notes:
        body.append(f"    {n}")
    return body


class GoogleStyle(CommentStyle):
    """Google-style Python docstrings (``Args:`` / ``Returns:`` / ``Note:``).

    Overrides the two hook methods only; the structured inputs are identical
    to :class:`PlainStyle`, so ``python.py`` is unchanged.  Python-only.
    """

    name = "google"
    label = "Google"
    description = "Google-style docstrings (Args / Returns / Note)"
    languages = frozenset({"python"})

    def file_header(self, meta: AlgoMeta, usage: UsageExample) -> list[str]:
        return _render(self.syntax, _google_header_body(meta, usage), indent=0)

    def doc_block(self, block: DocBlock, indent: int = 0) -> list[str]:
        return _render(self.syntax, _google_block_body(block), indent)
