"""Generate ``src/crcglot/_vectors.py`` -- independent CRC self-test goldens.

Cert-grade two-oracle agreement: each golden is computed by **anycrc** (crcany /
C) AND **crccheck** (pure-Python), which must agree, and each algorithm is
anchored to reveng's published ``check`` value.  Any disagreement aborts.

Both oracles are dev-only (the emitted module is pure data + a lookup -- no
runtime dependency).  The code generators embed these as self-test constants;
``tests/test_independent_vectors.py`` cross-checks crcglot's own engine.

Regenerate when the catalogue changes:

    uv run python scripts/gen_vectors.py
"""

from __future__ import annotations

from pathlib import Path

import anycrc
from crccheck.crc import Crc

from crcglot import ALGORITHMS

_OUT = Path(__file__).resolve().parent.parent / "src" / "crcglot" / "_vectors.py"

# Four fixed inputs.  The two large ones exercise byte-value coverage and length;
# the generated self-tests reproduce them with loops (no embedded array).
INPUTS: dict[str, bytes] = {
    "empty": b"",
    "check": b"123456789",
    "all_bytes": bytes(range(256)),
    "binary_1k": bytes((i * 167 + 13) & 0xFF for i in range(1024)),
}

_HEADER = '''\
"""Independent CRC self-test goldens -- AUTO-GENERATED, do not edit by hand.

Generated by ``scripts/gen_vectors.py``.  Each value is the CRC of one of four
fixed inputs, computed by TWO independent engines (anycrc + crccheck) that had
to agree, and (at the ``check`` input) anchored to reveng's published value.
The code generators embed these as self-test constants;
``tests/test_independent_vectors.py`` cross-checks crcglot's own engine.

Inputs: ``empty=b""``, ``check=b"123456789"``, ``all_bytes=bytes(range(256))``,
``binary_1k=bytes((i * 167 + 13) & 0xFF for i in range(1024))``.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from crcglot.catalogue import Crc

'''

_FOOTER = '''

_BY_PARAMS: dict[tuple[int, int, int, bool, bool, int], dict[str, int]] | None = None


def goldens_for(crc: "Crc") -> dict[str, int] | None:
    """The four self-test goldens for a catalogue ``Crc`` / ``AlgorithmInfo``.

    Keyed by parameter tuple so a renamed catalogue algorithm still resolves;
    returns ``None`` for a custom (non-catalogue) polynomial.
    """
    global _BY_PARAMS
    if _BY_PARAMS is None:
        from crcglot.catalogue import ALGORITHMS
        _BY_PARAMS = {
            (a.width, a.poly, a.init, a.refin, a.refout, a.xorout): VECTORS[n]
            for n, a in ALGORITHMS.items() if n in VECTORS
        }
    return _BY_PARAMS.get(
        (crc.width, crc.poly, crc.init, crc.refin, crc.refout, crc.xorout)
    )
'''


def _crccheck_calc(a, data: bytes) -> int:
    return Crc(
        width=a.width, poly=a.poly, initvalue=a.init,
        reflect_input=a.refin, reflect_output=a.refout, xor_output=a.xorout,
    ).calc(data)


def compute_vectors() -> dict[str, dict[str, int]]:
    """Compute every catalogue golden via two independent oracles.

    For each algorithm and each of the four fixed inputs, anycrc and crccheck
    must agree; the ``check`` input must additionally reproduce reveng's
    published value.  This is the cert-grade agreement the embedded self-tests
    rest on, factored out so a test can re-run the exact generation logic and
    prove the committed ``_vectors.py`` is a current, reproducible regeneration.

    Returns:
        ``{algorithm_name: {input_name: crc}}`` for every catalogue entry, in
        sorted-name order.

    Raises:
        ValueError: if the two oracles disagree on any value, or a ``check``
            value does not match the catalogue (reveng) anchor.

    Examples:
        >>> vectors = compute_vectors()
        >>> vectors["crc32"]["check"] == ALGORITHMS["crc32"].check
        True
    """
    vectors: dict[str, dict[str, int]] = {}
    for name in sorted(ALGORITHMS):
        a = ALGORITHMS[name]
        oracle = anycrc.CRC(a.width, a.poly, a.init, a.refin, a.refout, a.xorout)
        vals: dict[str, int] = {}
        for inp, data in INPUTS.items():
            v_anycrc = oracle.calc(data)
            v_crccheck = _crccheck_calc(a, data)
            if v_anycrc != v_crccheck:
                raise ValueError(
                    f"ORACLE DISAGREEMENT {name}/{inp}: "
                    f"anycrc=0x{v_anycrc:X} != crccheck=0x{v_crccheck:X}"
                )
            vals[inp] = v_anycrc
        if vals["check"] != a.check:
            raise ValueError(
                f"REVENG ANCHOR FAILED {name}: oracle=0x{vals['check']:X} != "
                f"catalogue.check=0x{a.check:X}"
            )
        vectors[name] = vals
    return vectors


def _render(vectors: dict[str, dict[str, int]]) -> str:
    """Render the goldens dict to the ``_vectors.py`` module source."""
    rows: list[str] = []
    for name in sorted(vectors):
        a = ALGORITHMS[name]
        vals = vectors[name]
        hexw = (a.width + 3) // 4
        body = ", ".join(f'"{inp}": 0x{vals[inp]:0{hexw}X}' for inp in INPUTS)
        rows.append(f'    "{name}": {{{body}}},')
    return (
        _HEADER
        + "VECTORS: dict[str, dict[str, int]] = {\n"
        + "\n".join(rows)
        + "\n}\n"
        + _FOOTER
    )


def main() -> None:
    vectors = compute_vectors()
    _OUT.write_text(_render(vectors), encoding="utf-8")
    print(
        f"wrote {len(vectors)} algorithms (anycrc==crccheck, reveng-anchored) "
        f"-> {_OUT}"
    )


if __name__ == "__main__":
    main()
