"""Regenerate EXAMPLES.md from the current state of the generators.

Run this script before tagging a release.  It walks ``LANGUAGES`` x
each variant the language supports, calls the generator for ``crc32``,
and emits a self-contained ``EXAMPLES.md`` with one collapsible
``<details>`` block per (language x variant) cell -- collapsed by
default so the page is scannable, expandable to read the code.

Usage:
    uv run python scripts/regenerate_examples.py

Effect:
    Overwrites ``EXAMPLES.md`` at the repo root.

The header prose is hardcoded below.  Edit it here if you want to
change what readers see above the gallery.

Verification: open the file in GitHub's preview / VS Code's preview
and confirm every block expands cleanly.  Or just diff the result --
the only changes between runs should be when generator output
genuinely changes.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Lazy-load to be runnable as a script from anywhere in the repo.
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))
from crcglot import LANGUAGES  # noqa: E402  (sys.path adjusted above)


_ALGORITHM = "crc32"


# Order languages by code; readers expect a stable layout.  Within
# each language, order variants from simplest (bitwise) to fastest
# (slice8 if supported).
_VARIANT_ORDER = ["bitwise", "table", "slice8"]

# Human-readable label per variant code.
_VARIANT_LABEL = {
    "bitwise": "bit-by-bit",
    "table": "table-driven",
    "slice8": "slice-by-8",
}

# CLI flag per variant ("" = no flag for default bit-by-bit).
_VARIANT_FLAG = {
    "bitwise": "",
    "table": "--table",
    "slice8": "--slice8",
}

# Code-fence info string per language.  Most just equal the LANGUAGES
# code key; exceptions get an explicit override below.  The human-readable
# label comes from ``LanguageInfo.display_name`` so adding a new language
# requires no edits to this script.
_FENCE_OVERRIDES = {
    "verilog": "systemverilog",  # GitHub Linguist recognizes this label
}


def _fence_for(code: str) -> str:
    return _FENCE_OVERRIDES.get(code, code)


_HEADER = """# crcglot generated code gallery

Every block below is the actual output of `crcglot` for the `crc32` \
algorithm under different language / implementation choices.  Reproduce any \
of them with the listed command.  Each file embeds a `_self_test()` that \
asserts against the reveng catalogue's canonical check value \
(`crc("123456789") == 0xCBF43926` for crc32).

Want a different algorithm?  Substitute the name (`crcglot list` for the \
full catalogue) and re-run the command.

All examples here use `crc32` (reflected; refin=true, refout=true, \
xorout=0xFFFFFFFF, ISO 3309 / Ethernet / PKZIP).  Non-reflected algorithms \
(e.g. `crc32-bzip2`) emit structurally different inner loops; see the \
source generators for the four shapes.

Every block is collapsed by default.  Click a heading to expand.  The \
Quick links section is a flat TOC of every (language x variant) cell -- \
useful for jumping straight to a single example.

This file is auto-generated by `scripts/regenerate_examples.py`.  Do not \
hand-edit; re-run the script instead.
"""


def _anchor_for(code: str, variant: str) -> str:
    """Stable anchor for (language, variant).  We emit explicit
    ``<a id="...">`` tags rather than relying on GitHub's auto-anchor
    from the rendered heading -- ``C`` and ``C#`` would collide
    (``#`` is stripped from auto-anchors) and ``—`` (em-dash)
    rendering is inconsistent across markdown parsers.
    """
    return f"example-{code}-{variant}"


def _quick_links() -> str:
    """Build the Quick links TOC -- one bullet per language, with
    inline links to each variant of that language.  Anchors are the
    explicit ids emitted before each ``<details>`` block.
    """
    lines = ["## Quick links", ""]
    for code in sorted(LANGUAGES.keys()):
        info = LANGUAGES[code]
        lang_label = LANGUAGES[code].display_name
        variants = [v for v in _VARIANT_ORDER if v in info.variants]
        links = [
            f"[{_VARIANT_LABEL[v]}](#{_anchor_for(code, v)})"
            for v in variants
        ]
        lines.append(f"- **{lang_label}**: " + " · ".join(links))
    lines.append("")
    return "\n".join(lines)


def _render_one(code: str, variant: str) -> str:
    """Render one collapsible ``<details>`` block for the (lang,
    variant) cell.  C is special because it emits a (header, source)
    pair; every other language emits a single string.
    """
    info = LANGUAGES[code]
    lang_label = info.display_name
    variant_label = _VARIANT_LABEL[variant]
    flag = _VARIANT_FLAG[variant]
    cmd = f"crcglot {code} {_ALGORITHM}"
    if flag:
        cmd += f" {flag}"
    fence = _fence_for(code)

    # Build kwargs for the generator call.
    kwargs = {}
    if variant == "table":
        kwargs["table"] = True
    elif variant == "slice8":
        kwargs["slice8"] = True

    result = info.generator(_ALGORITHM, **kwargs)
    assert result is not None, f"generator({code}, {_ALGORITHM}) returned None"

    parts: list[str] = []
    parts.append(f'<a id="{_anchor_for(code, variant)}"></a>')
    parts.append("")
    parts.append("<details>")
    parts.append("<summary>")
    parts.append("")
    parts.append(f"### {lang_label} — {variant_label}")
    parts.append("")
    parts.append("</summary>")
    parts.append("")
    parts.append("```bash")
    parts.append(cmd)
    parts.append("```")
    parts.append("")
    if isinstance(result, tuple):
        # C: (header, source) pair.
        header, source = result
        parts.append("**Header (`.h`)**")
        parts.append("")
        parts.append(f"```{fence}")
        parts.append(header)
        parts.append("```")
        parts.append("")
        parts.append("**Source (`.c`)**")
        parts.append("")
        parts.append(f"```{fence}")
        parts.append(source)
        parts.append("```")
    else:
        parts.append(f"```{fence}")
        parts.append(result)
        parts.append("```")
    parts.append("")
    parts.append("</details>")
    parts.append("")
    return "\n".join(parts)


def main() -> None:
    out: list[str] = [_HEADER, _quick_links()]
    for code in sorted(LANGUAGES.keys()):
        info = LANGUAGES[code]
        for variant in _VARIANT_ORDER:
            if variant not in info.variants:
                continue
            out.append(_render_one(code, variant))
    target = Path(__file__).parent.parent / "EXAMPLES.md"
    target.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {target} ({target.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
