"""Regenerate EXAMPLES.md from the current state of the generators.

Run this script before tagging a release.  It walks ``LANGUAGES`` x
each variant the language supports, calls the generator for ``crc32``,
and emits a self-contained ``EXAMPLES.md`` with one collapsible
``<details>`` block per (language x variant) cell -- collapsed by
default so the page is scannable, expandable to read the code.

Usage:
    uv run python scripts/regenerate_examples.py

Effect:
    Overwrites ``EXAMPLES.md`` at the repo root.

The header prose is hardcoded below.  Edit it here if you want to
change what readers see above the gallery.

Verification: open the file in GitHub's preview / VS Code's preview
and confirm every block expands cleanly.  Or just diff the result --
the only changes between runs should be when generator output
genuinely changes.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Lazy-load to be runnable as a script from anywhere in the repo.
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))
from crcglot import LANGUAGES  # noqa: E402  (sys.path adjusted above)
from crcglot.comments import (  # noqa: E402  (sys.path adjusted above)
    style_info,
    styles_for_language,
)


_ALGORITHM = "crc32"

# The comment-styles section renders one short algorithm in every doc
# style a language supports, so the cell-to-cell difference is the *style*,
# not the algorithm or the variant.
_STYLE_ALGORITHM = "crc32"
_STYLE_VARIANT = "bitwise"


# Order languages by code; readers expect a stable layout.  Within
# each language, order variants from simplest (bitwise) to fastest
# (slice8 if supported).
_VARIANT_ORDER = ["bitwise", "table", "slice8"]

# Human-readable label per variant code.
_VARIANT_LABEL = {
    "bitwise": "bit-by-bit",
    "table": "table-driven",
    "slice8": "slice-by-8",
}

# CLI flag per variant ("" = no flag for default bit-by-bit).
_VARIANT_FLAG = {
    "bitwise": "",
    "table": "--table",
    "slice8": "--slice8",
}

# Code-fence info string per language.  Most just equal the LANGUAGES
# code key; exceptions get an explicit override below.  The human-readable
# label comes from ``LanguageInfo.display_name`` so adding a new language
# requires no edits to this script.
_FENCE_OVERRIDES = {
    "verilog": "systemverilog",  # GitHub Linguist recognizes this label
}


def _fence_for(code: str) -> str:
    return _FENCE_OVERRIDES.get(code, code)


_HEADER = """# crcglot generated code gallery

Every block below is the actual output of `crcglot` for the `crc32` \
algorithm under different language / implementation choices.  Reproduce any \
of them with the listed command.  Each file embeds a `_self_test()` that \
asserts against the reveng catalogue's canonical check value \
(`crc("123456789") == 0xCBF43926` for crc32).

Want a different algorithm?  Substitute the name (`crcglot list` for the \
full catalogue) and re-run the command.

All examples here use `crc32` (reflected; refin=true, refout=true, \
xorout=0xFFFFFFFF, ISO 3309 / Ethernet / PKZIP).  Non-reflected algorithms \
(e.g. `crc32-bzip2`) emit structurally different inner loops; see the \
source generators for the four shapes.

Every block is collapsed by default.  Click a heading to expand.  The \
Quick links section is a flat TOC of every (language x variant) cell -- \
useful for jumping straight to a single example.

Past the variant gallery, a [Comment styles](#comment-styles) section shows \
the same algorithm rendered in every documentation style each language \
supports (`--comment`), so you can match the doc convention your codebase \
already uses.

This file is auto-generated by `scripts/regenerate_examples.py`.  Do not \
hand-edit; re-run the script instead.
"""


_COMMENT_STYLES_INTRO = """## Comment styles

The `--comment` flag picks the documentation style of the generated code; \
the algorithm and inner loop are identical.  Each block below is `crc32` \
(bit-by-bit) in one style, so you can match the convention your codebase \
already uses (Doxygen, JavaDoc, rustdoc, Google/NumPy/reST docstrings, ...).  \
`plain` -- professional comments in the language's native syntax -- is the \
default and is shown alongside each language's specialized styles for \
comparison.  Verilog and VHDL support only `plain` and are omitted here."""


def _anchor_for(code: str, variant: str) -> str:
    """Stable anchor for (language, variant).  We emit explicit
    ``<a id="...">`` tags rather than relying on GitHub's auto-anchor
    from the rendered heading -- ``C`` and ``C#`` would collide
    (``#`` is stripped from auto-anchors) and ``—`` (em-dash)
    rendering is inconsistent across markdown parsers.
    """
    return f"example-{code}-{variant}"


def _quick_links() -> str:
    """Build the Quick links TOC -- one bullet per language, with
    inline links to each variant of that language.  Anchors are the
    explicit ids emitted before each ``<details>`` block.
    """
    lines = ["## Quick links", ""]
    for code in sorted(LANGUAGES.keys()):
        info = LANGUAGES[code]
        lang_label = LANGUAGES[code].display_name
        variants = [v for v in _VARIANT_ORDER if v in info.variants]
        links = [
            f"[{_VARIANT_LABEL[v]}](#{_anchor_for(code, v)})"
            for v in variants
        ]
        lines.append(f"- **{lang_label}**: " + " · ".join(links))
    lines.append("")
    return "\n".join(lines)


def _details_block(
    anchor: str,
    heading: str,
    cmd: str,
    result: str | tuple[str, str],
    fence: str,
    *,
    subtitle: str | None = None,
) -> str:
    """Render one collapsible ``<details>`` block.

    Shared by the variant gallery and the comment-styles section.  C is
    special because it emits a (header, source) pair; every other language
    emits a single string.  ``subtitle`` is an optional italic line under the
    heading (the comment-styles section uses it for the style description).
    """
    parts: list[str] = [
        f'<a id="{anchor}"></a>',
        "",
        "<details>",
        "<summary>",
        "",
        f"### {heading}",
        "",
        "</summary>",
        "",
    ]
    if subtitle:
        parts += [f"_{subtitle}_", ""]
    parts += ["```bash", cmd, "```", ""]
    if isinstance(result, tuple):
        # C: (header, source) pair.
        header, source = result
        parts += [
            "**Header (`.h`)**", "", f"```{fence}", header, "```", "",
            "**Source (`.c`)**", "", f"```{fence}", source, "```",
        ]
    else:
        parts += [f"```{fence}", result, "```"]
    parts += ["", "</details>", ""]
    return "\n".join(parts)


def _render_one(code: str, variant: str) -> str:
    """Render the (language, variant) gallery cell for ``crc32``."""
    info = LANGUAGES[code]
    flag = _VARIANT_FLAG[variant]
    cmd = f"crcglot {code} {_ALGORITHM}" + (f" {flag}" if flag else "")

    result = info.generator(_ALGORITHM, variant=variant)
    assert result is not None, f"generator({code}, {_ALGORITHM}) returned None"

    return _details_block(
        _anchor_for(code, variant),
        f"{info.display_name} — {_VARIANT_LABEL[variant]}",
        cmd,
        result,
        _fence_for(code),
    )


def _style_anchor(code: str, style: str) -> str:
    """Stable anchor for a (language, comment-style) cell.

    Kept distinct from :func:`_anchor_for` (``example-…``) so the styles
    section never collides with the variant gallery.
    """
    return f"style-{code}-{style}"


def _render_style_one(code: str, style: str) -> str:
    """Render one (language, comment-style) cell for ``crc32`` bit-by-bit."""
    info = LANGUAGES[code]
    si = style_info(style)
    cmd = f"crcglot {code} {_STYLE_ALGORITHM} --comment {style}"

    result = info.generator(
        _STYLE_ALGORITHM, variant=_STYLE_VARIANT, comment_style=style
    )
    assert result is not None, f"generator({code}, {style}) returned None"

    return _details_block(
        _style_anchor(code, style),
        f"{info.display_name} — {si.label}",
        cmd,
        result,
        _fence_for(code),
        subtitle=si.description,
    )


def _comment_styles_section() -> str:
    """Build the "Comment styles" section.

    One sub-block per (language, style) for every language that supports
    more than the universal ``plain`` style -- so a reader can pick the doc
    convention matching their codebase.  Plain-only targets (Verilog, VHDL)
    are omitted: there is nothing to compare.
    """
    multi = [c for c in sorted(LANGUAGES) if len(styles_for_language(c)) > 1]

    lines = [_COMMENT_STYLES_INTRO, ""]
    # Mini-TOC: one bullet per language, a link per style.
    for code in multi:
        links = " · ".join(
            f"[{style_info(s).label}](#{_style_anchor(code, s)})"
            for s in styles_for_language(code)
        )
        lines.append(f"- **{LANGUAGES[code].display_name}**: {links}")
    lines.append("")

    for code in multi:
        for style in styles_for_language(code):
            lines.append(_render_style_one(code, style))
    return "\n".join(lines)


def main() -> None:
    out: list[str] = [_HEADER, _quick_links()]
    for code in sorted(LANGUAGES.keys()):
        info = LANGUAGES[code]
        for variant in _VARIANT_ORDER:
            if variant not in info.variants:
                continue
            out.append(_render_one(code, variant))
    out.append(_comment_styles_section())
    target = Path(__file__).parent.parent / "EXAMPLES.md"
    target.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {target} ({target.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
